### ISSUE TITLE
[Enhancement] R5402 rule message

### ISSUE THREAD

**Issue by bowserax** [cnescatlab/sonar-cnes-python-plugin#18]
Here is a proposition of rule message enhancement : 

"**R5402**
Consider dropping use of os.%s.
<p> Used when environment variables are accessed. A program should not rely on its execution environment. </p>
<p> The project properties such as login, database access URL, system properties, etc. could be managed using a properties file (XML, YAML or JSON format).  
Python modules like "configparser" (python version > 3.10.7) could be useful to manage properties along the project development.</p>"

**Comment by louisjdmartin** [comment]
The message is added in dev branch.
It will be included in the next version of the plugin.
